name: Manual Backup for RDS and EFS

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Trigger RDS Backup using AWS Backup
      run: |
        echo "Triggering RDS backup..."
        aws backup start-backup-job \
          --resource-arn arn:aws:rds:${{ secrets.AWS_REGION }}:863518438036:db:database-1 \
          --iam-role-arn arn:aws:iam::863518438036:role/service-role/AWSBackupDefaultServiceRole \
          --backup-vault-name my-backup-vault  # Replace with your backup vault name
          
    - name: Trigger EFS Backup using AWS Backup
      run: |
        echo "Triggering EFS backup..."
        aws backup start-backup-job \
          --resource-arn arn:aws:efs:${{ secrets.AWS_REGION }}:863518438036:file-system:fs-0d9a9eba270b57421 \
          --iam-role-arn arn:aws:iam::863518438036:role/service-role/AWSBackupDefaultServiceRole \
          --backup-vault-name my-backup-vault  # Replace with your backup vault name
          --backup-plan-id 635c8e4e-a268-40e6-9823-58e53d0b2441  # Use your actual backup plan ID
